spring:
  config:
    import:
      - api-config.yml
      - app-config.yml
      - persistence-config.yml
      - security-config.yml

---
spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

logging:
  level:
    kkomo: DEBUG

---
spring:
  config:
    activate:
      on-profile: main
      spring:
  thymeleaf:
    prefix: classpath:templates/thymeleaf/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: true

logging:
  level:
    kkomo: DEBUG
