spring:
  config:
    import:
      - api-config.yml
      - app-config.yml
      - persistence-config.yml
      - security-config.yml
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    kkomo: DEBUG

---
spring:
  config:
    activate:
      on-profile: main

logging:
  level:
    kkomo: DEBUG
