name: test pull-request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    environment: test
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up JDK21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Create environment variable file
        run: |
          touch .env.test
          echo "${{ secrets.ENV }}" >> .env.test

      - name: Cache Gradle packages
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Test with Gradle
        run: ./test.sh

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml